apiVersion: v1
kind: Pod
metadata: 
  name: emp-dir-pod
spec: 
  containers:
    - name: emp-dir
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-vol 
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-vol
      emptyDir: {}