apiVersion: v1
kind: Pod
metadata:
  name: ierm-pod
  labels:
    app: init-env-res-multi
spec:
  containers:
    - name: ubuntu
      image: ubuntu:20.04
      command: ["sh", "-c", "while true; do echo Hello; sleep 5; done"]
      env:
        - name: ENVIRONMENT
          value: "development"
        - name: AUTHOR
          value: "Titas Majumder"
        - name: APP_VERSION
          value: "1.0.0"
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "600Mi"
          cpu: "400m"

    - name: nginx
      image: nginx:latest
      ports: 
        - containerPort: 80
      env:
        - name: ENVIRONMENT
          value: "development"
        - name: AUTHOR
          value: "Titas Majumder"
        - name: APP_VERSION
          value: "1.0.0"
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "200m"
  initContainers:
    - name: busy
      image: busybox
      command: ["sh", "-c", "echo Hello; sleep 5"]