apiVersion: v1
kind: Pod
metadata:
  name: init-cont 
spec:
  initContainers:
    - name: busy
      image: busybox
      command: ["sh", "-c", "echo Hello; sleep 5"]
  
  containers:
    - name: nginx
      image: nginx:latest
      ports: 
        - containerPort: 80