apiVersion: v1
kind: Pod
metadata:
  name: nginx-busy
  labels:
    app: nb-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do echo Hello; sleep 5; done"]
    