apiVersion: v1
kind: Pod
metadata:
  name: res-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "400Mi"
          cpu: "200m"